[package]
name = "nix-spp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnix = "0.11.0"
rowan = "0.15.0"
clap = { version = "4.0.32", features = ["derive"] }
ignore = "0.4.19"
anyhow = "1.0.69"
